// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvlMk0lvXkcAW0BWH5aH_SDVRTaVkMv6E',
    appId: '1:610010499765:web:030a71acb2aa69be910cfc',
    messagingSenderId: '610010499765',
    projectId: 'getuone-2737f',
    authDomain: 'getuone-2737f.firebaseapp.com',
    storageBucket: 'getuone-2737f.firebasestorage.app',
    measurementId: 'G-V1FCT1P4XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVafWEnzqYmSsLvNXXx8A9OMuY4HbwT5s',
    appId: '1:610010499765:android:e32d17b93d9f6f79910cfc',
    messagingSenderId: '610010499765',
    projectId: 'getuone-2737f',
    storageBucket: 'getuone-2737f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmomFA7Lp7UpwSyM5fUsO-oxhdPRuaWG0',
    appId: '1:610010499765:ios:c50873c0e505caf5910cfc',
    messagingSenderId: '610010499765',
    projectId: 'getuone-2737f',
    storageBucket: 'getuone-2737f.firebasestorage.app',
    iosBundleId: 'com.example.getuone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmomFA7Lp7UpwSyM5fUsO-oxhdPRuaWG0',
    appId: '1:610010499765:ios:c50873c0e505caf5910cfc',
    messagingSenderId: '610010499765',
    projectId: 'getuone-2737f',
    storageBucket: 'getuone-2737f.firebasestorage.app',
    iosBundleId: 'com.example.getuone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvlMk0lvXkcAW0BWH5aH_SDVRTaVkMv6E',
    appId: '1:610010499765:web:1d7c907938012dfa910cfc',
    messagingSenderId: '610010499765',
    projectId: 'getuone-2737f',
    authDomain: 'getuone-2737f.firebaseapp.com',
    storageBucket: 'getuone-2737f.firebasestorage.app',
    measurementId: 'G-PLRW0QHMTY',
  );
}
